### ISSUE TITLE
keys shall not be urls, but they should reside in xml files

### ISSUE THREAD

**Issue by torbenh3** [Linutronix/elbe#103]
url-list contains the option to give a key-url. This should be extended to give the key in a raw format inside XML to avoid men in the middle attacks.

**Comment by manut** [comment]
Being able to use keys from keyservers would be also nice

**Comment by lzrdkng** [comment]
I'm working on this.

As for now, I added the following:

<raw-key>
----- BEGIN PGP ... -----
...
----- END PGP ... -----

</raw-key>

and

<key-server pool="eu.pool.sks-keyservers.net">0x36AA35FF22BB8F84</key-server>


Is this a good format?

**Comment by lzrdkng** [comment]
An other format could be to make a complex type like 'pgp-key' and assign to it some attribute:

```
<key type="raw">
----- BEGIN PGP ... -----
...
----- END PGP ... -----

</key>
````

`<key type="server" pool="eu.pool.sks-keyservers.net">0x36AA35FF22BB8F84</key>`

The default type would be to "url" to maintain compatibility

**Comment by bgermann** [comment]
The pool attribute should contain the protocol (hkp://, hkps://, ...) that is used for the key transfer.

**Comment by lzrdkng** [comment]
> The pool attribute should contain the protocol (hkp://, hkps://, ...) that is used for the key transfer.

From GPG(1):

> The format of the name is a URI: `scheme:[//]keyservername[:port]' The scheme is the type of keyserver: "hkp" for the HTTP (or compat‐
>               ible) keyservers, "ldap" for the LDAP keyservers, or "mailto" for the Graff email keyserver. Note that your particular installation of GnuPG  may  have  other
>               keyserver types available as well. Keyserver schemes are case-insensitive.

This will be documented in the XML

**Comment by torbenh3** [comment]
merged into elbe master now.
keyserver download is not implemented.

open a new issue for it, if you are interested in it.
