### ISSUE TITLE
python-npyscreen not available for stretch

### ISSUE THREAD

**Issue by jogness** [Linutronix/elbe#117]
It is not possible to install elbe-debianize under stretch because python-npyscreen is not available for stretch. Installing the python-npyscreen package from http://debian.linutronix.de/elbe-common/pool/main/p/python-npyscreen/ works just fine, so I expect it is simply a problem of python-npyscreen not being listed as a stretch package in the elbe-common repo.

**Comment by manut** [comment]
i added the package to the stretch Packages file on the mirror.
