### ISSUE TITLE
packages added via finetuning are not included on iso images

### ISSUE THREAD

**Issue by jogness** [Linutronix/elbe#123]
There are situations where it is necessary to add packages via finetuning. For example, if another architecture is needed (dpkg --add-architecture) and packages from that architecture must be installed. Some problems that could arise when implementing this feature/fix:
-  the local project repos may need to support multiple architectures (the above example shows this)
- there may not be source packages available (for example, finetuning with "dpkg -i" for packages not on mirrors)

**Comment by manut** [comment]
using <command> in finetuning is for some kind of 'hacking'.

What you really want to have is multiarch support. This should not be done in finetuning, instead vote and hack on this: https://github.com/Linutronix/elbe/issues/81
