### ISSUE TITLE
build --build-bin/sources broken with security mirror

### ISSUE THREAD

**Issue by jogness** [Linutronix/elbe#125]
elbe 2.1

If security mirrors are listed in the XML, elbe is unable to build with --build-bin and/or --build-sources specified.

    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/elbepack/asyncworker.py", line 116, in execute
        skip_pbuild=self.skip_pbuilder)
      File "/usr/lib/python2.7/dist-packages/elbepack/elbeproject.py", line 215, in build
        self.xml.validate_apt_sources ( m , self.arch )
      File "/usr/lib/python2.7/dist-packages/elbepack/elbexml.py", line 207, in validate_apt_sources
        raise ValidationError (["Repository %s can not be validated" % u])
    ValidationError: Repository http://security.debian.org/dists/stretch/updates/main/binary-amd64/Release can not be validated

The relevant XML entries:

    <mirror>
      <primary_host>httpredir.debian.org</primary_host>
      <primary_path>/debian</primary_path>
      <primary_proto>http</primary_proto>
      <url-list>
        <url>
          <binary>http://security.debian.org stretch/updates main</binary>
          <source>http://security.debian.org stretch/updates main</source>
        </url>
      </url-list>

If the --build-bin and --build-sources options are both missing, there is no problem building the image. Or if the security servers are removed from the url-list, then there is no problem building with --build-bin and/or --build-sources.

**Comment by manut** [comment]
fixed by 9030d6f4dbf48604afba1f2209e2f8793ceef03e
