### ISSUE TITLE
pbuilder aarch64: multithreading problems

### ISSUE THREAD

**Issue by djfun** [Linutronix/elbe#128]
When multiple threads are used in an aarch64 pbuilder, the build fails (segfault of the process in the pbuilder, sometimes tcg error messages from qemu).
My current workaround is putting a recent version of qemu-aarch64-static (2.10.0) into the initvm (before creating the pbuilder) instead of the installed 2.1.2

Edit: It seems to work also with 2.8.0, the version from jessie-backports

**Comment by manut** [comment]
There is 'elbe-specific' version of qemu at
http://debian.linutronix.de/elbe-common/pool/main/q/qemu-elbe/
it is installed via 'elbepack/init/preseed.cfg.mako'. This package needs to be updated to 2.10.0.
