### ISSUE TITLE
xsdtoasciidoc skips at least some attributes

### ISSUE THREAD

**Issue by manut** [Linutronix/elbe#129]
<simpleContent>
      <extension base="rfs:string">
        <attribute name="pin" type="string" use="optional">
          <annotation>
            <documentation>
              Pin-Priority of packages from this source.
            </documentation>

Is not available here:

https://elbe-rfs.org/docs/sphinx/article-elbe-schema-reference.html

**Comment by manut** [comment]
also e.g. the finetuning tag <command> is missing

**Comment by torbenh3** [comment]
complex types which are not sequences do not get examples generated for them.

**Comment by torbenh3** [comment]
notes on the original issue:

we iterate over all xsd nodes. but we only have handlers for:

 * `ELEM = "{http://www.w3.org/2001/XMLSchema}element"`
 * `CPLX = "{http://www.w3.org/2001/XMLSchema}complexType"`
 * `SIMP = "{http://www.w3.org/2001/XMLSchema}simpleType"`
