### ISSUE TITLE
race condition with env vars 

### ISSUE THREAD

**Issue by torbenh3** [Linutronix/elbe#132]
env vars a global in process.
We have to reset http_proxy and friends, when they are empty.

This points at a race condition, though.

Identify where they are used, and either use execve to set them.
Or make sure that the right vars come to RpcAptCache.

**Comment by virraaj** [comment]
Can you please give some more information to reproduce the issue? and can you please verify if the issue is still present in elbe v14.4?

**Comment by bgermann** [comment]
On 3rd Dec 2018, @manut wrote: "patches are on the ML but not tested so far"
@virraaj Please check if you can identify the patches on [elbe-devel](https://lists.linutronix.de/pipermail/elbe-devel/)

**Comment by virraaj** [comment]
@bgermann the question here is about reproducing. I don't have enough information on what to test even if I guess any patches.

**Comment by bgermann** [comment]
The patches will probably provide more info for reproducing.

**Comment by bene42** [comment]
More information needed. Please reopen if nessesary.
