### ISSUE TITLE
care about encoding in licence.txt/xml generation

### ISSUE THREAD

**Issue by manut** [Linutronix/elbe#133]
But the current code raises an exception that interrupts the hole build.
This means, if you use a package that triggers an encoding exception you are
not able to build the image, that's a nogo.

I'm quite unhappy with the licence code. It's hard to understand and
undocumented, also the encoding issue needs to be resolved.

Also it is not py3 compatible

**Comment by manut** [comment]
according to https://www.debian.org/doc/debian-policy/#copyright-information all copyright files must be encoded in utf-8. 

So elbe can expect that and if handling the file fails, we should handle this gently and recommend to file a bug for the package that cause the exception.

**Comment by torbenh3** [comment]
there is an error attribute, that defaults to strict, when an encoding error is seen.
use errors="replace" and remove the exception handling then.
