### ISSUE TITLE
remove python 2 compatibility code

### ISSUE THREAD

**Issue by manut** [Linutronix/elbe#136]
as soon as the transition to py3 is completed the following commits need to be reverted

189cd630e7347f374724dcf0aac1afc4f2ae657b
py3: debian - override tests

efc7b37b66ace6a3c6014bfdd17c8c0dc3d49af5
py3: make - use python3 interpreter to call xsdtoasciidoc

c6a19f1dbb1e3c83b46b5139831f6a6b6714ada4
add an iter() implementation to treeutils

**Comment by manut** [comment]
07e1b93795221b095db51e364d47d3cb7c6eef36
py3: debian/python-buildenv-postinst: call elbe with py2

**Comment by manut** [comment]
one blocker is: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=877783

**Comment by manut** [comment]
https://github.com/arskom/spyne/issues/113

**Comment by bgermann** [comment]
arskom/spyne#617
