### ISSUE TITLE
libvirt QEMU Driver error is printed when "elbe initvm create" is executed

### ISSUE THREAD

**Issue by anna-marialx** [Linutronix/elbe#140]
When executing "elbe initvm create" with elbe v2.9.2 the following error is printed:
"libvirt: QEMU Driver error : Domain not found: no domain with matching name 'initvm' ".

libvirt prints to stdout or stderr:

    def __init__(self, node, initvmNeeded = True):
        # The tag initvmNeeded is required in order to be able to run `elbe initvm create`                                                                         
        self.conn = libvirt.open("qemu:///session")
        try:
            self.initvm = self.conn.lookupByName('initvm')

Nevertheless the initvm is created successfully.

**Comment by manut** [comment]
The lookup should not be done before the initvm is created, so this is a bug.
But it's safe to ignore the printed error.
