### ISSUE TITLE
sysroot: packages like libsqlite3-dev not end up in the sysroot

### ISSUE THREAD

**Issue by mischelebuha** [Linutronix/elbe#142]
I have an application that builds against sqlite. Now I would like to create a sysroot. In my xml is the package libsqlite3-0 included. But in sysroot the header files are missing. I think the problem caused from the nameing of the sqlite dev package.

Runtime: libsqlite3-0
Dev: libsqlite3-dev

Is there another solution to get the dev package in my sysroot, but not in my target build?

**Comment by manut** [comment]
Nope, naming shouldn't be the problem. We look which binary packages come from the same dsc than the binary package in the package list and is in the 'devel' section.

But you need to specify the libsqlite3-0 package explicitly in your pkg-list.

**Comment by mischelebuha** [comment]
I use the xml in 'setsel' mod and i have the package [libsqlite3-0](https://packages.debian.org/stretch/libsqlite3-0) in my 'pkg-list'.
BTW, the [libsqlite3-dev](https://packages.debian.org/stable/libdevel/libsqlite3-dev) package is only in the 'libdevel' and not in the 'devel' section.

I looked at the python scripts and find only this code section:
[dev_list = [s for s in self.cache if (s.candidate.source_name in src_list and s.name.endswith ('-dev'))]](https://github.com/Linutronix/elbe/blob/f971494fff175c08b7468def4373ab9d6f17d80e/elbepack/rpcaptcache.py#L111)

**Comment by manut** [comment]
Indeed, this is the line that should detect the libsqlite3-dev package. However i have no idea what's wrong with the statement.

**Comment by mischelebuha** [comment]
The fact is that the libsqlite3-dev package not end up in the sysroot.

> Nope, naming shouldn't be the problem. We look which binary packages come from the same dsc than the binary package in the package list and is in the 'devel' section.

Where can I find this logic in the Python scripts?

**Comment by manut** [comment]
On Thu, Feb 01, 2018 at 09:27:32AM +0000, mischelebuha wrote:
> The fact is that the libsqlite3-dev package not end up in the sysroot.
> 
> > Nope, naming shouldn't be the problem. We look which binary packages come from the same dsc than the binary package in the package list and is in the 'devel' section.
> 
> Where can I find this logic in the Python scripts?

Nowhere. You've already found the line. The logic checks if the package-name ends
with '-dev'. I just didn't remember it correctly.

**Comment by bgermann** [comment]
libsqlite3-0 ends up in mark_install_devpkgs' `ignore_pkgs` parameter. That is the reason for libsqlite3-dev not being installed.

**Comment by torbenh3** [comment]
commit log did not mention closes #142 correctly
