### ISSUE TITLE
pbuilder on wheezy targets: incompatible "-jauto" option

### ISSUE THREAD

**Issue by manut** [Linutronix/elbe#147]
Date: Wed, 24 Jan 2018 15:28:22 +0000
From: Lukasz Walewski <lwalewski@s-can.at>
To: "elbe-devel@linutronix.de" <elbe-devel@linutronix.de>
Message-ID: <1516807674733.67924@s-can.at>
Subject: [elbe-devel] pbuilder on wheezy targets: incompatible "-jauto" option
Content-Type: multipart/mixed; boundary="===============5657836292687724043=="

[-- Attachment #1 --]
[-- Type: multipart/alternative, Encoding: 7bit, Size: 5.4K --]

Hi,

When building Debian packages for <suite>wheezy</suite> images with pbuilder, elbe calls pdebuild with --debbuildopts "-jauto", which is supported by dpkg
+since version 1.17.10:

dpkg-buildpackage(1):

      -j, --jobs[=jobs|auto]
              Number  of  jobs  allowed  to  be  run  simultaneously,  number  of  jobs matching the number of online
              processors if auto is specified (since dpkg 1.17.10), or unlimited number if  jobs  is  not  specified,

However, pbuilder for a <suite>wheezy</suite> image is (not surprisingly) created as Debian 7.x (wheezy) pbuilder:

running cmd +pbuilder --create --configfile "/var/cache/elbe/ID/pbuilderrc" --aptconfd
ir "/var/cache/elbe/ID/aptconfdir" --extrapackages git+
------------------------------------------------------------------------------
W: /.pbuilderrc does not exist
I: Distribution is wheezy.

and dpkg in Debian 7.x (wheezy) is 1.16.18, so pbuilder fails due to unrecognized option:

running cmd +cd "/var/cache/elbe/ID/pdebuilder/current"; pdebuild --debbuildopts "-jau
to -sa" --configfile "/var/cache/elbe/ID/pbuilderrc" --use-pdebuild-internal --buildre
sult "/var/cache/elbe/ID/pbuilder/result"+
[...]

I: Running /usr/bin/dpkg-buildpackage -rfakeroot -us -uc ${DEBBUILDOPTS}
dpkg-buildpackage: unknown option or argument -jauto
[...]

Command failed with errorcode 1

Package fails to build.

On the other hand "-jauto" is a convenient option esp. for large packages. Maybe elbe could emulate it on wheezy pbuilders with something similar to:

"-j$(nproc --all)"

???

Best,

Lukasz

**Comment by torbenh3** [comment]
we dont support wheezy anymore.
