### ISSUE TITLE
/dev/kvm permission denied error from within the docker container

### ISSUE THREAD

**Issue by QuickJack** [Linutronix/elbe#164]
The problem occurs after building and running Elbe (tested with 2.9.11) and logging in to the created docker container as root. When calling "elbe initvm create" the vm starts to build and after that, the operation is terminated with "Could not access KVM kernel module: Permission denied
failed to initialize KVM: Permission denied'". I have tested this with Ubuntu 14.04.

To resolve the problem, the following has to be done from within the container (see also step 5 from #154):

```
root@7db78791baea:/# ls -l /dev/kvm
crw-rw---- 1 root root 10, 232 May 25 10:57 /dev/kvm
root@7db78791baea:/# chgrp kvm /dev/kvm
root@7db78791baea:/# ls -l /dev/kvm
crw-rw---- 1 root kvm 10, 232 May 25 10:57 /dev/kvm
```

Simply adding "RUN chgrp kvm /dev/kvm" to the Dockerfile does not work because /dev/kvm is not accessible during the build operation. However, it could be an option to create an entry script which corrects the group ownership of /dev/kvm during runtime.

**Comment by manut** [comment]
fixed by e4b7818fe55c37e3550afe55f17833a4f60f0823
