### ISSUE TITLE
Is there a reason why Elbe is not available on Docker Hub?

### ISSUE THREAD

**Issue by QuickJack** [Linutronix/elbe#169]

**Comment by manut** [comment]
noone requested it so far.

**Comment by QuickJack** [comment]
It would be very nice to have a pre built docker image available on Docker Hub or a similar public registry. This way, we wouldn't have to compile the images ourselfs which is a time consuming task.

**Comment by manut** [comment]
cd elbe/contrib/dockerfile
make

..is not very time consuming on my machine.

But feel free to contact sales@linutronix.de if you want us, to include this and the upload to dockerhub in our release process. I think it would make sense, to also store a pre-generated initvm inside the container that is uploaded to dockerhub.
