### ISSUE TITLE
initvm version conflict

### ISSUE THREAD

**Issue by QuickJack** [Linutronix/elbe#190]
When creating the initvm I receive the following error:

```
elbe control create_project failed.
elbe v2.9.13 is used in initvm, this is not compatible with elbe v2.9.11 that is used on this machine. Please install same versions of elbe in initvm and on your machine.
```

My repository is still at v2.9.11. Is there a way to force the target version of initvm to be v2.9.11 instead of v2.9.13?

**Comment by manut** [comment]
thanks for your report, fixed by b923620f0d0efc9b23d10f13ee26472e6429f0b0
