### ISSUE TITLE
provide more flexible image compression

### ISSUE THREAD

**Issue by manut** [Linutronix/elbe#195]
in elbe-testing some images are stored as .gz

it would be nice to have an optin to specify the compression format and if an image should be compressed or not.

**Comment by jogness** [comment]
And if the uncompressed choice is chosen (which I would love), the image should be downloaded (via soap) and stored as a sparse file! (Using a sparse tarball as a temporary container for the soap transport could be a workaround in case dealing with sparse files is otherwise a problem.)

**Comment by manut** [comment]
fixed by 265ebe537ec2826ee6c2c559ed40711c1a36d310
