### ISSUE TITLE
elbe initvm still uses jessie

### ISSUE THREAD

**Issue by manut** [Linutronix/elbe#201]
jessie becomes oldoldstable if buster will be released.

It should be possible to use elbe-daemon on a current debian release.

**Comment by gajanak** [comment]
'Bug' is now more critical. Debian FTP doesn't provide http://ftp.de.debian.org//debian/dists/jessie/main/installer-amd64 anymore.  initvm will fail downloading.

**Comment by QuickJack** [comment]
@gajanak: See #215

**Comment by manut** [comment]
The issue is resolved within elbe 2.5 and elbe > 4.

http://lists.linutronix.de/pipermail/elbe-devel/2019-April/002169.html

**Comment by QuickJack** [comment]
@manut Many thanks for your response. I thought v3 is the current version of Elbe. But there is also v4 and v5. Which version is recommended/stable?
