### ISSUE TITLE
Mention "elbe preprocess" on schema validation errors

### ISSUE THREAD

**Issue by manut** [Linutronix/elbe#204]
variant=attributes and archivedir tags are valid things in XML that is put into elbe-preprocess. But they are not valid to be entered into the XML given to the initvm.

Currently we call validation only for XMLs going into the intivm. It would be nice, to have also a schema to validate the XML that is going into elbe-preprocess.

**Comment by bgermann** [comment]
I do not think that we should have an additional schema. However, when the validation errors, there should be a message that tells the user that this can only operate on preprocessed XMLs.

**Comment by bene42** [comment]
XML schema rework is not planed ATM.
