### ISSUE TITLE
elbe4: debian-installer breaks at "Select and install software"

### ISSUE THREAD

**Issue by bgermann** [Linutronix/elbe#211]
`elbe initvm create` aborts at "Select and install software" for Elbe v4. Yesterday I built one initvm successfully but later had the same issue that is reported by @jogness at http://lists.linutronix.de/pipermail/elbe-devel/2019-April/002254.html. So maybe it was an update on an Elbe dependency yesterday (afternoon) that broke it. I do not use any local mirror.
The full message looks like:

```
Select and install software  ... 10%... 20%... 31%... 40%... 50%... 61%... 70%... 80%... 90%
Select and install software
---------------------------

!! ERROR: Installation step failed

An installation step failed. You can try to run the failing item again from the
menu, or skip it and choose something else. The failing step is: Select and 
install software
[Press enter to continue]
```

**Comment by markusmoll** [comment]
I am experiencing the same problem.

**Comment by bgermann** [comment]
The stretch-backports kernel that was missing and caused this issue (see mail thread) is now available again.
