### ISSUE TITLE
qemu: Unsupported syscall: 383

### ISSUE THREAD

**Issue by bgermann** [Linutronix/elbe#212]
For an elbe armhf pbuilder building a package with man-db dependency I hit https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=891109. The process loops on "qemu: Unsupported syscall: 383". As almost every Debian package has a (transitive) build dependency on man-db this is going to hit other users as well. The bug is fixed for buster but the fixed version is not available in stretch-backports.

**Comment by manut** [comment]
I cannot reproduce this.

Can you describe how to reproduce this issue please.

**Comment by bgermann** [comment]
I cannot reproduce anymore as well, so closing this.

**Comment by bgermann** [comment]
This can be triggered with <buildtype>armhf</buildtype> ... <suite>buster</suite> ... <pbuilder><git revision='133c0bd417532663afc8cbaad852137dd34cdef9'>https://github.com/labgrid-project/labgrid.git</git></pbuilder>

**Comment by bgermann** [comment]
I guess moving the initvm to buster will fix the problem with buster's newer qemu version.
As long as this is not done the example hook /usr/share/doc/pbuilder/examples/D80no-man-db-rebuild can be registered for elbe's pbuilder runs.

**Comment by bgermann** [comment]
With a buster initvm this is fixed indeed.

**Comment by bgermann** [comment]
Fixed by 303a5d63d1e6193
