### ISSUE TITLE
elbe preprocess uses gzip compression

### ISSUE THREAD

**Issue by bgermann** [Linutronix/elbe#213]
The help message for `elbe preprocess` shows `--output=<xmlfile>` and the default file name is preprocess.xml. However, you get a gzipped file from it. So either the description or the behaviour should be updated.

**Comment by manut** [comment]
The idea of the gzipped xml was to reduce the transfer time between host and initvm.

**Comment by bgermann** [comment]
Nice. Thanks for including the change!
