### ISSUE TITLE
initvm grub.cfg has root=/dev/vda1 instead of root=UUID

### ISSUE THREAD

**Issue by jogness** [Linutronix/elbe#216]
With elbe 2, the /boot/grub/grub.cfg in the initvm used a UUID for the root= boot option. This was very useful because it allowed the initvm image to be used with or without virtio and even with other VM's like VMware or Virtual Box.

With elbe 5, grub.cfg contains root=/dev/vda1. This means that it is no longer possible to use the initvm image with anything other than qemu and virtio.

**Comment by oldiob** [comment]
This issue is solved on Buster

**Comment by bgermann** [comment]
Confirmed.
