### ISSUE TITLE
install_version is broken

### ISSUE THREAD

**Issue by manut** [Linutronix/elbe#218]
$ elbe control list_projects
elbe v6 is used in initvm, this is not compatible with elbe v7 that is used on this machine. Please install same versions of elbe in initvm and on your machine.
To install elbe v7 into the initvm use 'elbe control install_elbe_version'
$ elbe control install_elbe_version
elbe v6 is used in initvm, this is not compatible with elbe v7 that is used on this machine. Please install same versions of elbe in initvm and on your machine. To install elbe v7 into the initvm use 'elbe control install_elbe_version'
$ elbe control install_elbe_version --ignore-version-diff
elbe v6 is used in initvm, this is not compatible with elbe v7 that is used on this machine. Please install same versions of elbe in initvm and on your machine.
To install elbe v7 into the initvm use 'elbe control install_elbe_version'
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '7*' for 'python-elbe-buildenv' was not found
E: Version '7*' for 'elbe-soap' was not found
E: Version '7*' for 'python-elbe-common' was not found
E: Version '7*' for 'elbe-daemon' was not found
E: Version '7*' for 'elbe-schema' was not found
E: Version '7*' for 'python-elbe-bin' was not found

Error: apt returns 100

**Comment by hdengler** [comment]
There is a workaround for this bug:
- attach to initvm an login as root (elbe initvm attach)
- inside of the initvm:
  - update the package index (apt update)
  - update elbe packages (apt install python3-elbe-soap)
  - logout and detach

The versions should now be in sync.

**Comment by bgermann** [comment]
Closing as claimed in the commit reference.
