### ISSUE TITLE
noauth shouldn't be a global flag

### ISSUE THREAD

**Issue by manut** [Linutronix/elbe#220]
noauth is typically used, because a few local repos are unsigned. However the repos retrieved from upstream are typically correctly signed. So for those who have unsigned local repos it would be a security improvement to attach the noauth flag to just those repos.

**Comment by virraaj** [comment]
Hi @bgermann , is this issue already fixed using the patch series http://lists.linutronix.de/pipermail/elbe-devel/2019-August/003231.html mentioned in the issue referenced above?
