### ISSUE TITLE
there is no initvm global repo

### ISSUE THREAD

**Issue by manut** [Linutronix/elbe#221]
To share packages between multiple elbe builds inside an initvm it would be helpful to have a repo that is shared over all project builds inside the same initvm. It needs to be discussed how the destination of a pbuilder build is specified (project repo or global repo).

This could avoid that people create a repo on their localmachine because they are tired of uploading the packages to each elbe project before build. What actually is done and avoids the usage of elbe-initvm-submit.

**Comment by bgermann** [comment]
I do not think that we want to handle the complexity of this suggestion.
