### ISSUE TITLE
elbe validate does not expect "key"

### ISSUE THREAD

**Issue by gamgee** [Linutronix/elbe#229]
The schema for validating the xml files seems to be outdated

$ ./elbe validate examples/elbe-init-big-machine.xml
validation failed
examples/elbe-init-big-machine.xml:24 error Element 'key': This element is not expected.
examples/elbe-init-big-machine.xml:35 error Element 'key': This element is not expected.

**Comment by oldiob** [comment]
The validation is not preprocessing the files.  I'm fixing this.

**Comment by bgermann** [comment]
#204
