### ISSUE TITLE
missing qemu dependency

### ISSUE THREAD

**Issue by richardcochran** [Linutronix/elbe#23]
When running elbe under debian wheezy, the 'make' command fails when
starting qemu.  The error message is:

    kvm: -device virtio-rng-pci: Parameter 'driver' expects device type

Apparently wheezy's qemu (1.1.2+dfsg-6a+deb7u6) is either too old or was
compiled without a critical option.  Qemu from wheezy-backports works fine.

Elbe depends on qemu-utils and qemu-system, but without any version
restriction.  However it should depend on the minimal qemu version needed
in order to run properly.

Thanks,
Richard

**Comment by manut** [comment]
improved dependency qemu-kvm (>= 1:21)
