### ISSUE TITLE
buster does not build if /var is seperat mounted

### ISSUE THREAD

**Issue by jantronix** [Linutronix/elbe#230]
running cmd +chroot
/var/cache/elbe/da424bf5-d182-4fdf-9f3a-d6e4ced12746/imagemnt
update-initramfs -u -k all+
------------------------------------------------------------------------------
update-initramfs: Generating /boot/initrd.img-4.19.0-5-amd64
mktemp: failed to create directory via template
'/var/tmp/mkinitramfs_XXXXXX': No such file or directory
update-initramfs: failed for /boot/initrd.img-4.19.0-5-amd64 with 1.
------------------------------------------------------------------------------

**Comment by jogness** [comment]
FWIW, this (now outdated) [patch](http://lists.linutronix.de/pipermail/elbe-devel/2018-January/000996.html) was created to prevent this problems. Although I will admit the whole mounting/unmounting code needs a rewrite. Lots of copy paste. Lots of hard-coded cram.
