### ISSUE TITLE
Using LOCALMACHINE results in permanent sources.list entry

### ISSUE THREAD

**Issue by bgermann** [Linutronix/elbe#235]
When LOCALMACHINE is used within an Elbe XML, a line `deb ... http://10.0.2.2 ...` is appended to /etc/apt/sources.list. It should be removed after finishing the build so that any apt operation on the resulting system shall not give any warning or error.

**Comment by oldiob** [comment]
Is this still the case as of today?  

Which sources.list are you refering to, i.e. which rfs?

**Comment by bgermann** [comment]
The target rfs.
