### ISSUE TITLE
Reasons for <debootstrappkgs>

### ISSUE THREAD

**Issue by Blackjack92** [Linutronix/elbe#237]
Hello all,

I have seen an elbe configuration with `<debootstrappkgs>`  set. What are the reasons for these pkgs? 
Furthermore, I have not found any detailed documentation for them, is there any additional advanced documentation?

Thanks in advance!

**Comment by bgermann** [comment]
The only documentation is in the schema: https://github.com/Linutronix/elbe/blob/5cdc8a8fea96789a22c067288efaad0144e6f347/schema/dbsfed.xsd#L67

debootstrap is the program used to set up the elbe build environment. The debootstrappkgs are directly installed after that phase.
