### ISSUE TITLE
elbe debianize kernel firmware handling incomplete

### ISSUE THREAD

**Issue by torbenh3** [Linutronix/elbe#241]
firmware is showing up in linux-image*.install even when its not built using "make firmware"
the logic is broken

**Comment by yegorich** [comment]
What about the following workaround:

1. create `FW_PATH` unconditionally
2. in `override_dh_auto_install` create a dummy file: `touch $(FW_PATH)/dummy`

This way, the build process won't break if no firmware is built.

**Comment by bgermann** [comment]
Fixed by 174fc85cc2d3c2a5770f5cfe608cebdc31b26000
