### ISSUE TITLE
Yocto like SDK installer fails on find $native_sysroot/lib -name "ld-linux*"

### ISSUE THREAD

**Issue by jneuhauser** [Linutronix/elbe#246]
Hello elbe devs,

since some time I have problems with the sdk installer script.
Earlier, shortly after announcing the feature, I was able to install the SDK with the self-extracting archive installer without any problems.
I have now built a root file system with SDK for buster and for stretch and installing the SDK does not work for both.
I also tried installing the SDK on different debian versions in an x86 VM, but always without success.

Here is the output of the SDK installer:
```
user@debian-vm:~/projects/elbe-rootfs$ ./setup-elbe-sdk-arm-linux-gnueabihf-buster-armhf-base-rootfs-1.0.sh 
ELBE buster-armhf-base-rootfs 1.0 SDK installer
===============================================
Enter target directory for SDK (default: /opt/elbe-sdk-arm-linux-gnueabihf-buster-armhf-base-rootfs-1.0): 
You are about to install the SDK to "/opt/elbe-sdk-arm-linux-gnueabihf-buster-armhf-base-rootfs-1.0". Proceed[Y/n]? Y
[sudo] password for user: 
Extracting SDK........................done
Setting it up...SDK could not be set up. Relocate script unable to find ld-linux.so. Abort!
```

The installation of the SDK always stops at the same place and I don't understand why.

If i take a look into the prepended shell script of the self-extracting archive it fails at:
```
# fix dynamic loader paths in all ELF SDK binaries
native_sysroot=$target_sdk_dir/sysroots/host
dl_path=$($SUDO_EXEC find $native_sysroot/lib -name "ld-linux*")
if [ "$dl_path" = "" ] ; then
        echo "SDK could not be set up. Relocate script unable to find ld-linux.so. Abort!"
        exit 1
fi
```
If i execute the command manually then the find command returns four files:
```
user@debian-vm:~/projects/elbe-rootfs$ find /opt/elbe-sdk-arm-linux-gnueabihf-buster-armhf-base-rootfs-1.0/sysroots/host -name "ld-linux*"
/opt/elbe-sdk-arm-linux-gnueabihf-buster-armhf-base-rootfs-1.0/sysroots/host/usr/lib64/ld-linux-x86-64.so.2
/opt/elbe-sdk-arm-linux-gnueabihf-buster-armhf-base-rootfs-1.0/sysroots/host/usr/arm-linux-gnueabihf/lib/ld-linux-armhf.so.3
/opt/elbe-sdk-arm-linux-gnueabihf-buster-armhf-base-rootfs-1.0/sysroots/host/usr/arm-linux-gnueabihf/lib/ld-linux.so.3
/opt/elbe-sdk-arm-linux-gnueabihf-buster-armhf-base-rootfs-1.0/sysroots/host/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
```

Probably anyone has a clue why the SDK installation is broken since some time?

**Comment by bgermann** [comment]
A patch is available at http://lists.linutronix.de/pipermail/elbe-devel/2019-October/003575.html

This will be included in the next Elbe version.
