### ISSUE TITLE
elbe chg_archive deletes xml comments

### ISSUE THREAD

**Issue by richardcochran** [Linutronix/elbe#25]
Running 'elbe chg_archive' does not preserve xml comments but rather deletes
them without any kind of warning.  This command really should be polite and leave
the comments alone when updating the <archive> section.  After all, somebody's
important notes or other critical information may be in the comment blocks.

Thanks,
Richard

**Comment by manut** [comment]
This is caused, by loading the XML in our parser, adding the archive/changing the archive tag and let the
parser write it back to disk. (The parser ignores comments.) On a first look, i can't find any settings for the
parser to keep the comments. Maybe it's better to use sth like 'sed' here? :-/

**Comment by cmhe** [comment]
Another option would be introducing a "comment" tag with arbitrary content. But that would be a bit hackish.

**Comment by manut** [comment]
this is fixed in elbe 1.9.x
