### ISSUE TITLE
initvm proxy used for target images

### ISSUE THREAD

**Issue by jogness** [Linutronix/elbe#250]
If an initvm is created with the "http_proxy" environment variable set, the initvm uses a proxy for installing its packages. This can be seen in:

    /etc/apt/apt.conf
    /apt/apt.conf.d/50elbe

However, when I try to build a target, the proxy is used for the target as well. (I do not want it to use the proxy for the target.) Since my proxy does not have the target architecture (armhf), it aborts:

    [ERROR] Failed to build the Apt Cache.
    Probable cause might be:
      - Problems with internet connection
      - Broken mirrors
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/elbepack/asyncworker.py", line 182, in execute
        skip_pbuild=self.skip_pbuilder)
      File "/usr/lib/python2.7/dist-packages/elbepack/elbeproject.py", line 524, in build
        self.install_packages(self.buildenv)
      File "/usr/lib/python2.7/dist-packages/elbepack/elbeproject.py", line 838, in install_packages
        raise AptCacheUpdateError(e)
    AptCacheUpdateError: Error Updating rpcaptcache: E:Failed to fetch http://security.debian.org/debian-security/dists/buster/updates/main/binary-armhf/Packages  404  Not Found [IP: my.proxy.ip.address 8888], E:Some index files failed to download. They have been ignored, or old ones used instead.

Note that it **did** get through the base installation. It was when it tried to get the package list for the server (security) in url-list that it died.

In order to build the target image, I needed to comment out the contents of **both** files in the initvm:

    /etc/apt/apt.conf
    /apt/apt.conf.d/50elbe

The only thing interesting in my target XML is that I am using the security servers as well:

    <mirror>
            <primary_host>ftp.de.debian.org</primary_host>
            <primary_path>debian</primary_path>
            <primary_proto>http</primary_proto>
            <url-list>
                    <url>
                            <binary>
                                     http://security.debian.org/debian-security buster/updates main
                            </binary>
                    </url>
            </url-list>
    </mirror>

**Comment by bene42** [comment]
Not planed ATM.
