### ISSUE TITLE
Support for grub-legacy in buster

### ISSUE THREAD

**Issue by mrelyb** [Linutronix/elbe#251]
Hello Elbe-Team,

we need support for grub-legacy in buster. Currently we have many devices in the field running with jessie and grub-legacy. When updating them in the field to buster we do not want to take the risk to replace the bootloader in place and leave many devices unbootable.
So is it possible to support grub-legacy for buster images?

Thanks!

**Comment by bgermann** [comment]
A first patch series is available at http://lists.linutronix.de/pipermail/elbe-devel/2020-January/003743.html

**Comment by bgermann** [comment]
Included with 828ca92702de
