### ISSUE TITLE
Multiple project/preference tags not possible

### ISSUE THREAD

**Issue by mrelyb** [Linutronix/elbe#252]
When using multiple project/preference tags validation fails with 
`Element 'preference': This element is not expected. Expected is one of ( noauth, raw-preference, suite, buildimage, preseed ).`
I need to set the priority of multiple repos: 
- set buster-backports prio to 900 to use backports by default and 
- set prio of dotnet-buster repo to 50 to avoid using wrong packages from this repo.

**Comment by bgermann** [comment]
A workaround is using raw-preference instead, which takes syntax of an apt preference file. Would that be okay for you?

**Comment by mrelyb** [comment]
That would be ok for me.
