### ISSUE TITLE
Why does "No sources for package" crash the build?

### ISSUE THREAD

**Issue by coveritytest** [Linutronix/elbe#257]
I get the following errors in v12.2 and the build crashes:

[ERROR] No sources for package 'firmware-realtek-20190114-2'
[ERROR] No sources for package 'firmware-ti-connectivity-20190114-2'

Why and how to solve this? Posted the log.txt here: https://pastebin.pl/view/2ad80392

**Comment by bgermann** [comment]
Add "http://ftp.de.debian.org/debian/ buster non-free" to your source mirrors.
