### ISSUE TITLE
elbe hdimg with grub broken

### ISSUE THREAD

**Issue by richardcochran** [Linutronix/elbe#26]
When creating an image with \<grub-install /\>, elbe creates a grub configuration
that passes 'root=/dev/poop1' on the kernel command line.

Funny?  Yes.
Useful?  No.

Thanks,
Richard

**Comment by richardcochran** [comment]
This issue appears only with custom kernels (made with "make deb-pkg").
To work around this problem, add the following debs into \<pkg-list\>:

- initramfs-tools
- klibc-utils
- kmod
- libklibc
- libuuid-perl
- linux-base

**Comment by manut** [comment]
added a patch directory to elbe that includes the required changes on the kernel debian packaging
