### ISSUE TITLE
elbe fails with a fresh install on Debian 10 (buster) and the elbe from git

### ISSUE THREAD

**Issue by Collin01** [Linutronix/elbe#264]
Elbe fails on a fresh install on debian10.

Steps to reproduce:
- Install debian 10 in a vm.
- install packages: 
  apt install python python-debian python-mako python-lxml python-apt python-gpg python-suds python-libvirt qemu-utils qemu-kvm p7zip-full make
- git clone https://github.com/Linutronix/elbe.git
- cd elbe
- ./elbe initvm create ./examples/armhf-ti-beaglebone-black.xml

it produce this output:
(Please see attachment)
[log.txt](https://github.com/Linutronix/elbe/files/4574350/log.txt)

**Comment by codelectron** [comment]
I think you are missing the libvirt related installation and further configuration steps like here

https://elbe-rfs.org/docs/sphinx/article-quickstart.html?highlight=adduser#create-initvm-and-submit-xml-files

**Comment by oldiob** [comment]
See this issue <https://github.com/Linutronix/elbe/issues/248>

**Comment by bgermann** [comment]
There was no feedback and therefore I am closing this as duplicate.
