### ISSUE TITLE
Errors in the build is not visible in the log.txt

### ISSUE THREAD

**Issue by Collin01** [Linutronix/elbe#265]
Errors in the build cannot be read from the project log.
Build aborts with an error, without an error entry in the log.

Here are a log from a example build.
Build abort with info:
[INFO] Build finished with Error

[log test.txt](https://github.com/Linutronix/elbe/files/4587136/log.test.txt)

**Comment by bgermann** [comment]
[ERROR] No sources for package 'libfdisk1-2.29.2-1+deb9u1+revpi1'
...
[ERROR] No sources for package 'raspberrypi-kernel-9.20200228-4.9.76+revpi1'
