### ISSUE TITLE
InitVM create fails with default initvm

### ISSUE THREAD

**Issue by vincentdemaertelaere-excentis** [Linutronix/elbe#275]
When building the initvm using `elbe initvm --directory /path/to/initvm`, the Debian installation fails.

Some investigation shows that, the elbe-keyring.gpg in the APT configuration is only readable by user root and not by the user the installer uses to run apt (user _apt).

Running on Debian 10.4
Running ELBE from the linutronix repository (ELBE version 12.4)

**Comment by oldiob** [comment]
This should be fix on master
