### ISSUE TITLE
package list validation error when using wildcards in package version

### ISSUE THREAD

**Issue by mrelyb** [Linutronix/elbe#276]
If I use wildcards in package versions like `<pkg version="3.11\*">tls-additional-licences-cpx</pkg>` I will get a package list validation error, even if the matching package was found and installed correctly:

`[ERROR] Package 'tls-additional-licences-cpx' version '3.11\*' does not match installed version 3.11.0~RC2-81763`

**Comment by bgermann** [comment]
How about leaving out the escape \ ?

**Comment by mrelyb** [comment]
Doesn't work either:
`[ERROR] Package 'tls-additional-licences-cpx' version '3.11*' does not match installed version 3.11.0~RC2-81763`

**Comment by bgermann** [comment]
[Patch available](https://lists.linutronix.de/pipermail/elbe-devel/2021-January/005185.html)
