### ISSUE TITLE
elbe v12.5: 'on_src_cd="False"' is broken if source-package has different name than the binary-package

### ISSUE THREAD

**Issue by pzimmermann-dh** [Linutronix/elbe#277]
After upgrading to version 12.5, using 'on_src_cd="False"' at a package doesn't work anymore if its source package has another name than the binary package.

As an example, for our Buster rootFS, we have one software which needs the "libmariadbclient18" library of Stretch (the newer version of that software isn't available for armhf). So that we don't have to include the complete Stretch repo, we only took that software and the "libmariadbclient18" library into an extra repository and did not include their source packages.
In our XML-file the library is included with: <code>\<pkg on_src_cd="False"\>libmariadbclient18\</pkg\></code>

In version 12.4 this did work, but in version 12.5 the build process stops at the creation of the source-CD with the error:
<code>[ERROR] No sources for package 'mariadb-10.1-10.1.44-0+deb9u1'</code>

I did look into the code and I think that I found the problem:
In "elbepack/cdroms.py" in line 30 (in function "add_source_pkg"):
``` 
if pkg in forbid:
    return
```
I added some logging for myself and found that **pkg** contains the name of the **source-package** (here <code>mariadb-10.1</code>), while the list in **forbid** contains the names of the **binary-packages** (here <code>libmariadbclient18</code>) which does not match and the package is not skipped.

So if the binary package and its source package do not have the same name (which is very common) 'on_src_cd="False"' won't have any effect.

**Comment by bene42** [comment]
More info needed. Please reopen if nessesary.
