### ISSUE TITLE
How to change repository

### ISSUE THREAD

**Issue by smartdabao** [Linutronix/elbe#279]
It is not a bug, but I do not know where to ask questions, so I post it here. 
I want to use 'ftp.cn.debian.org' instead of 'ftp.de.debian.org' to speed up the process. But when I modify primary_host tag in xml, the initvm create command still download initrd-cdrom.gz from 'ftp.de.debian.org'.
How to change it? Do I have to replace 'ftp.de.debian.org' with 'ftp.cn.debian.org' in the whole elbe project?
Thank you.

**Comment by bgermann** [comment]
Look at example elbe-init-big-machine.xml which has an initvm XML section which holds the mirrors for the initvm. After that section you can have project and target sections as with the other examples.

**Comment by smartdabao** [comment]
Thank you for your reply.
