### ISSUE TITLE
python3-elbe-updated fails to install

### ISSUE THREAD

**Issue by vincentdemaertelaere-excentis** [Linutronix/elbe#288]
When installing python3-elbe-updated in the target root image, it fails with the error message that elbe-updated isn't installed.

When tracing back the issue, it seems that the postinst/prerm maintainer scripts of the debian package still reference elbe-updated while precompiling the python scripts.  Since the package was renamed to python3-elbe-updated, it should reference the new name instead of the old one.

I've sent the patch file to the elbe-devel mailing list, but still queued for moderator approval it seems.

**Comment by bgermann** [comment]
Closed via dc15ae48efb0983dd6c5705a34ee6d6323d75025
