### ISSUE TITLE
I can't use root password after the image setup (Elbe 13)

### ISSUE THREAD

**Issue by szigetiszabolcs80** [Linutronix/elbe#290]
Hi,
 I can't use root password after the image setup with the newest Elbe 13. I had ssh problem too with the latest 12 main version. Please help me: how can I setup an older version? The 12.2 worked well. I need to set it up. 
 Best Regards

**Comment by bgermann** [comment]
Please use Elbe 13.1 which solves the login problem (See e01acd18dbbbbd6ec14c8131de86b8d689bc61f8). If you still want to use an older version, force the installation of an older version via apt or aptitude.
