### ISSUE TITLE
elbe get_archive doesn't work

### ISSUE THREAD

**Issue by shifty91** [Linutronix/elbe#293]
elbe get_archive doesn't work and yields error: `Error writing archive`

Reproduce:
`mkdir foo;
echo asd > foo/asd;
elbe chg_archive rfs.xml foo;
elbe get_archive rfs.xml foo.tar.bz2`

Elbe: v13.1

**Comment by bgermann** [comment]
[Patch](https://lists.linutronix.de/pipermail/elbe-devel/2021-March/005229.html) available

**Comment by bgermann** [comment]
Fixed with 57f816420fa476452da5c5c17084392c0329ec46
