### ISSUE TITLE
In elbe v13.2 when using noauth setting pyhton complains about not initialized variable keyring

### ISSUE THREAD

**Issue by mrelyb** [Linutronix/elbe#297]
When building image with "noauth" setting in project set, python complains about an uninitialized variable "keyring"

        if not self.xml.is_cross(host_arch):
            if self.xml.has("project/noauth"):        --> variable "keyring" not set in this branch
                cmd = '%s --no-check-gpg --arch=%s "%s" "%s" "%s"' % (
                    strapcmd, arch, suite, self.rfs.path, primary_mirror)
            else:
                if self.xml.has("project/mirror/cdrom"):
                    keyring = ' --keyring="%s"' % (
                        self.rfs.fname('/elbe.keyring'))
                else:
                    keyring = ''

                cmd = '%s --arch=%s %s "%s" "%s" "%s"' % (
                    strapcmd, arch, keyring, suite, self.rfs.path, primary_mirror)

            try:
                self.cdrom_mount()
                if keyring:                     ---> ERROR
                    do('apt-key --keyring "%s" add "%s/targetrepo/repo.pub"' % (
                        self.rfs.fname('/elbe.keyring'),
                        self.rfs.fname("cdrom")))
                do(cmd)

**Comment by bgermann** [comment]
[Patch available](https://lists.linutronix.de/pipermail/elbe-devel/2021-March/005263.html).

**Comment by mrelyb** [comment]
Patch works, thanks!
