### ISSUE TITLE
Ubuntu Focal not in  elbe/elbepack/debianreleases.py

### ISSUE THREAD

**Issue by koberbe** [Linutronix/elbe#298]
Hello everyone,
I am unable to build an Ubuntu Focal image because `focal` is missing in `elbe/elbepack/debianreleases.py`. Once it is added, it works.

Best regards,
Kai

**Comment by bgermann** [comment]
Patch available: https://lists.linutronix.de/pipermail/elbe-devel/2021-August/005457.html

**Comment by koberbe** [comment]
Great, thanks.
