### ISSUE TITLE
Build from existing RFS

### ISSUE THREAD

**Issue by fmg-dave** [Linutronix/elbe#303]
Hello and thanks for the great tool you have created.

I have a scenario where I use elbe to generate two root file systems for two different purposes. The only difference between the two is that one contains a few more packages and some extra fine tuning. As a means to reduce build times (we have some limitations, that mean we cannot build in parallel), is it technically possible to 'seed' a build with an exiting rfs to build on top of? In other words, the end goal would be to build the first rfs like normal, then the xml for the second rfs would take in the first rfs and add some packages, do some fine tuning and produce the second rfs.

**Comment by bgermann** [comment]
Not really. What you can use to have one common xml is the variant xml property.
