### ISSUE TITLE
Improve error message on invalid repo

### ISSUE THREAD

**Issue by mrelyb** [Linutronix/elbe#309]
Recently I built an image which stopped with an error "Failed to build the Apt Cache". I tried to fix my own packages but that was not the reason for the error. After digging around some time I found that the update of the repo did not work and that the repo was therefore not vaild. 
It would be better to show the exacter error message of "apt" instead of just "Failed to build the Apt Cache" which could have several reasons.

[ERROR] Failed to build the Apt Cache. 
Probable cause might be: 
- Problems with internet connection 
- Broken mirrors 
Traceback (most recent call last): 
File "/usr/lib/python3/dist-packages/elbepack/elbeproject.py", line 993, in install_packages 
self.get_rpcaptcache(env=target).update() 
File "<string>", line 2, in update 
File "/usr/lib/python3.7/multiprocessing/managers.py", line 811, in _callmethod 
raise convert_to_error(kind, result) 
apt.cache.FetchFailedException: W:Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:1 and /etc/apt/sources.list:2, W:Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:1 and /etc/apt/sources.list:2, W:Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:1 and /etc/apt/sources.list:2, E:Release file for http://136.230.124.133/debian_mirror/debian-buster-security/dists/buster/updates/InRelease is expired (invalid since 7h 19min 47s). Updates for this repository will not be applied. 
During handling of the above exception, another exception occurred: 
Traceback (most recent call last): 
File "/usr/lib/python3/dist-packages/elbepack/asyncworker.py", line 186, in execute 
skip_pbuild=self.skip_pbuilder) 
File "/usr/lib/python3/dist-packages/elbepack/elbeproject.py", line 603, in build 
self.install_packages(self.buildenv) 
File "/usr/lib/python3/dist-packages/elbepack/elbeproject.py", line 995, in install_packages 
raise AptCacheUpdateError(e) 
elbepack.elbeproject.AptCacheUpdateError: Error Updating rpcaptcache: W:Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:1 and /etc/apt/sources.list:2, W:Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:1 and /etc/apt/sources.list:2, W:Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:1 and /etc/apt/sources.list:2, E:Release file for http://136.230.124.133/debian_mirror/debian-buster-security/dists/buster/updates/InRelease is expired (invalid since 7h 19min 47s). Updates for this repository will not be applied. 
elbe coltrol wait_busy /var/cache/elbe/15a3584a-0a8d-4393-8d6a-ad8c2c630952 failed! 
source.xml (Current source.xml of the project) 
validation.txt (Package list validation result) 
elbe-report.txt (Report) 
log.txt (Log file) 
##[error]Bash wurde mit dem Code "255" beendet.

**Comment by bene42** [comment]
Not planed ATM.
