### ISSUE TITLE
Boot problem

### ISSUE THREAD

**Issue by SerMel13** [Linutronix/elbe#325]
Hello,
Could you help me with unbootable elbe image? 

I created elbe image via "initvm submit ...". There were no error messages. Then I wrote the result sda.img.tar.gz to sda of VM (via tar xf0z and dd).

The boot process hangs before switching root without any warnings or errors (on VirtualBox and Qemu-KVM). 

The grub command and partitions layout seems to be correct. Is there any simple way to turn on "debug mode in initrd" for elbe images (without patching initrd file and some other tricks)?

**Comment by SerMel13** [comment]
![Screenshot from 2022-03-11 06-22-35](https://user-images.githubusercontent.com/85332258/157809987-4b094a29-096e-498c-bafc-58a56166e7b7.png)

**Comment by bgermann** [comment]
How are there no errors? There are plenty of them. Most probably you have a GPT layout problem.

**Comment by SerMel13** [comment]
![Screenshot from 2022-03-11 10-15-14](https://user-images.githubusercontent.com/85332258/157838172-d8977cd2-31c6-43eb-9c96-d0b9d78c1e85.png)

**Comment by SerMel13** [comment]
Ran parted from LIveCD and remove DVD from VM.
Still hangling.

**Comment by SerMel13** [comment]
Sorry for not updating. Adding devtmpfs.mount=1 to the linux command in grub config helped.
