### ISSUE TITLE
Building an ARM distribution without KVM installed

### ISSUE THREAD

**Issue by sureshjoshi** [Linutronix/elbe#326]
I've been testing ELBE on the build machines I've already provisioned on which I create my embedded linux distributions (Buildroot or Yocto via Docker), and I wanted to try ELBE as a comparison.

Unfortunately, I've been unable to get anywhere so far. 

My build machines do not have KVM extensions, so I cannot use libvirt or kvm. Running `elbe initvm create ...` fails on a `libvirtError` about not being able to connect to the socket (because it doesn't exist), and the Docker container fails out earlier on the kvm check.

I tried creating a DigitalOcean droplet, but it has the same KVM nested virtualization problem.

I saw another issue about using the daemon directly, however when I try running `elbe daemon --soap`, I get consecutive Python `ModuleNotFoundError`s. I try to get past them one at a time, but I'm eventually stuck on `no module named parted`.

If I can successfully get Debian installation working with my custom Linux kernel, I'll definitely buy a hardware box for this - but until now, it's been unnecessary. 

Does anyone have any recommendations of what I could try?

**Comment by bgermann** [comment]
You need to install python3-elbe-daemon and python3-elbe-soap when you want to run the daemon on a machine.
Then you should not have Module errors.
