### ISSUE TITLE
Elbe Docs not available/empty

### ISSUE THREAD

**Issue by martinbu** [Linutronix/elbe#342]
I have noticed that the content of [Elbe Docs](https://elbe-rfs.org/docs/sphinx/index.html) has been empty for a while. Maybe since the 14.5 release?

Does something went wrong here?

**Comment by bgermann** [comment]
That is a known issue. I am working on it.

**Comment by bgermann** [comment]
The info on the sphinx generated website is also available in git.

**Comment by bgermann** [comment]
I have reverted the docs to the last known-good version.

**Comment by d4nuu8** [comment]
> I have reverted the docs to the last known-good version.

I think this is still a issue. There is only the man-page of `elbe-add` available:
![Screenshot from 2022-11-03 09-42-56](https://user-images.githubusercontent.com/10478331/199678664-3f4df2a2-20b7-42cd-b21f-0ba4d1fc3a60.png)

**Comment by bgermann** [comment]
Yes, I know. It will be rectified with the next version. Please just switch to a different version on the side bar for now.
