### ISSUE TITLE
Creating initvm in docker doesn't work

### ISSUE THREAD

**Issue by danielmeer** [Linutronix/elbe#344]
Hi,

I can build, start and connect to the docker container by using the provided dockerfile in the _contrib/_ directory.

But when running `elbe initvm create`, it doesn't do anything except displaying an error message every few seconds:
```
elbe@987bc96de8be:/elbe$ elbe initvm create
libvirt: XML-RPC error : Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory
libvirt: XML-RPC error : Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory
libvirt: XML-RPC error : Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory
```

If I abort the command, I get this:
```
elbe@987bc96de8be:/elbe$ elbe initvm create
libvirt: XML-RPC error : Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory
libvirt: XML-RPC error : Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory
libvirt: XML-RPC error : Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory
^CTraceback (most recent call last):
  File "/usr/lib/python3/dist-packages/elbepack/initvmaction.py", line 87, in __init__
    self.conn = libvirt.open("qemu:///system")
  File "/usr/lib/python3/dist-packages/libvirt.py", line 255, in open
    if ret is None:raise libvirtError('virConnectOpen() failed')
libvirt.libvirtError: Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/elbe", line 60, in <module>
    cmdmod.run_command(sys.argv[2:])
  File "/usr/lib/python3/dist-packages/elbepack/commands/initvm.py", line 89, in run_command
    action = InitVMAction(args[0])
  File "/usr/lib/python3/dist-packages/elbepack/initvmaction.py", line 498, in __init__
    InitVMAction.__init__(self, node, initvmNeeded=False)
  File "/usr/lib/python3/dist-packages/elbepack/initvmaction.py", line 95, in __init__
    time.sleep(10)
KeyboardInterrupt
```

The behavior is the same on ELBE v14.6 and v14.2. My host system is an Ubuntu 22.04.

Any help or pointers would be appreciated.

**Comment by danielmeer** [comment]
The docker container is installing ELBE 14.3 from the Linutronix repository. When I run the v14.6 git checkout I get a different error:
```
elbe@987bc96de8be:/elbe$ ./elbe initvm create
Traceback (most recent call last):
  File "./elbe", line 57, in <module>
    mod = __import__(modname)
  File "/elbe/elbepack/commands/initvm.py", line 11, in <module>
    from elbepack.initvmaction import InitVMAction, InitVMError
  File "/elbe/elbepack/initvmaction.py", line 28, in <module>
    from elbepack.repodir import RepodirError, Repodir
  File "/elbe/elbepack/repodir.py", line 40
    bin_el.text = f"http://LOCALMACHINE:{httpd.server_address[1]} {repo[1]}"
                                                                           ^
SyntaxError: invalid syntax
```

**Comment by bgermann** [comment]
You need at least Python 3.6 to run Elbe.
You should install Elbe via the Debian packages.

**Comment by bgermann** [comment]
Using Docker, you are on your own. You need the libvirt damon running. Look at the elbe documentation which libvirt groups the running user has to be in.

**Comment by manut** [comment]
If you want to use Elbe in a container it might be interesting to just call elbe buildchroot as shown here: https://github.com/Linutronix/elbe/blob/master/contrib/k8s/jenkins-shared-lib/vars/elbebuild.groovy

The used Containerfile is also there:
https://github.com/Linutronix/elbe/blob/master/contrib/k8s/Dockerfile

But consider that the container needs to run in privileged mode and qemu binfmt things are available..

Than it is sth very similar to what you do with debos —disable-fakemachine

**Comment by danielmeer** [comment]
Thanks for the hints! But I think I will give up for the moment.

One of the reasons I wanted to use a container instead of a VM is to use all of my computer's resources when building an image. But as everything is running inside the initvm, I wouldn't have gained anything anyway.
