### ISSUE TITLE
Starting the initvm Failed

### ISSUE THREAD

**Issue by xliang76** [Linutronix/elbe#347]
I tried to create the image with x86_64-pc-hdimage-gnome3.xml from example.
I got error 
ibvirt: QEMU Driver error : internal error: qemu unexpectedly closed the monitor: 2022-10-15T17:26:06.524883Z qemu-system-x86_64: The -accel and "-machine accel=" options are incompatible
any idea?

**Comment by bgermann** [comment]
Your host system's libvirt and qemu versions have to be compatible.

**Comment by xliang76** [comment]
I am running from Ubuntu 22.04 and elbe is checkout from this repo.
How do I check if the libvirt and qemu version is compatible?
Thank you

**Comment by bgermann** [comment]
which versions are they? Any backports/third party repos (except for elbe?

**Comment by xliang76** [comment]
I didn't add third party repos as it was fresh Ubuntu install.
And the libvirt is 8.0.0 The qemu is 6.2.0

**Comment by bgermann** [comment]
Hm... The commit that changed things is at https://gitlab.com/qemu-project/qemu/-/commit/976e8c54142586285f71f524308e4715f6e04e2d at the qemu side. But that is quite old.
Please explain the other question in more detail a new issue.

**Comment by xliang76** [comment]
thank you for this. I tried to track down the function call, it run into the libvirt. I can't find it in my system. So, it must be built one. Looks like it need to install other version or manually update it. 
For the second question, it is not issue. It is a learning question.

**Comment by bgermann** [comment]
This was observed on bookworm, so I am reopening.
