### ISSUE TITLE
404 -> https://www.linutronix.de/projects/Elbe/dbsfed.xsd

### ISSUE THREAD

**Issue by rnixx** [Linutronix/elbe#357]
Hi,

I just wanted to build my first rootfs using elbe and immediately failed due to a 404 when trying to download the schema file.

https://github.com/Linutronix/elbe/blob/master/elbepack/xmlpreprocess.py#L286

I installed elbe from recent master.

Not sure if the file is included in the dist, but why not read from there since it is included in the sources anyway?

**Comment by bgermann** [comment]
It is read from there and this has already been answered. Please search the issues.
