### ISSUE TITLE
Login fails

### ISSUE THREAD

**Issue by coveritytest** [Linutronix/elbe#364]
I have a freshly generated RFS with elbe v14.6.1, which starts up to the login prompt. I then cannot login although I enter the correct credentials (it does not work with the root user or with a user created specifically for this purpose). I have no idea why. The login is done via ttyS0, other ways are currently not available. I can't say if it is board specific. I don't understand why no login is possible. I already tried to manipulate the security settings to get in and see the logging entries. So far unsuccessful. Any ideas what could be the reason?

**Comment by bgermann** [comment]
Please try replacing passwd with passwd_hashed. The current elbe default rounds might be too costly.
See also 2d415893ae05d0aacb937a4bdaa782d2520cb663
