### ISSUE TITLE
libvirt.libvirtError: Cannot access storage file

### ISSUE THREAD

**Issue by yegorich** [Linutronix/elbe#370]
On Ubuntu 22.04.1 LTS I get the following error when creating initvm:

`libvirt: Storage Driver error : Cannot access storage file '/home/user/elbe/initvm/initvm.img' (as uid:64055, gid:108): Permission denied`

I have fixed it via editing `/etc/libvirt/qemu.conf` and setting `user` to myself. This [article](https://ostechnix.com/solved-cannot-access-storage-file-permission-denied-error-in-kvm-libvirt/) provides background info.

Can this issue be fixed in elbe code?

**Comment by bgermann** [comment]
@a-darwish Is this the bug that you reported to me some days ago?

**Comment by bgermann** [comment]
It is already in the documentation that you have to add the elbe running user to the libvirt group.

**Comment by bgermann** [comment]
The quickstart doc also says:
`adduser <youruser> libvirt-qemu`

**Comment by yegorich** [comment]
No, this doesn't help. AFAIK, you don't have to add a user to `libvirt-qemu`. Only `kvm` and `libvirt` groups matter.

**Comment by yegorich** [comment]
This issue seems to have something to do with the newer libvirt version (new security policy). See this [thread](https://bbs.archlinux.org/viewtopic.php?id=275126). 

I ended up adding read permissions to libvirt-qemu user to my home folder. Looks like specifying such permissions for initvm folder is not enough.
