### ISSUE TITLE
only one build in parallel is possible

### ISSUE THREAD

**Issue by manut** [Linutronix/elbe#38]
% ./elbe initvm submit examples/x86_64-pc-hdimg-gnome3.xml --keep-files --skip-build-bin --skip-build-sources 
elbe control create_project failed.
Server returned error:

project in directory /var/cache/elbe/8c3888f4-4652-4ae8-82ed-6f98c71a3545 of user root is currently busy and cannot be closed

Giving up

This is because the soap daemon holds a single project-manager instance. I think we need to extend the project manager handling mulitple projects.

**Comment by bene42** [comment]
Outdated due to containers.
