### ISSUE TITLE
Is it possible to update from stretch to bullseye directly via elbe-updated?

### ISSUE THREAD

**Issue by coveritytest** [Linutronix/elbe#380]
As the title says, is it possible to update from stretch to bullseye directly via elbe-updated or do we have to update to buster first?

**Comment by bgermann** [comment]
As elbe-updated operates via apt, you rely on the packages being able to upgrade. In Debian, a stable update is only tested to work to the next stable version, not the next-next stable version. So I would go with the intermediate update.
