### ISSUE TITLE
Cannot install – repository is empty

### ISSUE THREAD

**Issue by philippludwig** [Linutronix/elbe#396]
The Quickstart guide tells us to use the repository @ http://debian.linutronix.de/elbe/, but the server only yields a 403 error.

**Comment by t-8ch** [comment]
How did you access the repository?
With a browser directly you will receive a 403.

This URL is meant to be used to configure apt which will use it as base to construct other URLs which do work.
See for example http://debian.linutronix.de/elbe/dists/bookworm/Release

**Comment by philippludwig** [comment]
I see. Adding `dists/bookworm/Release` did not occur to me.

Other debian mirrors, e.g. http://ftp.be.debian.org/debian/, have a working page on the base URL. So I just assumed that the repository is broken.
