### ISSUE TITLE
Wine on base image

### ISSUE THREAD

**Issue by 7eXx** [Linutronix/elbe#415]
i would like include wine in my base image that i'm current working on.
I added "winehq" url binary and its raw-key.
Instructions from official wine site mention to execute "dpkg --add-architecture i386".
How can i tweak this thing and also add "winehq-stable" in my package list (pkg-list)?

**Comment by 7eXx** [comment]
By now i'm editing finetuning adding:
```
<command>dpkg --add-architecture i386</command>
<command>apt-get update</command>
<command>apt-get install wine32 -y</command>
```

**Comment by t-8ch** [comment]
To be honest this does sound like a fringe usecase and I'm a bit reluctant to add first-class support for it.
I think the finetuning solution works well enough, no?

FYI the packages from winehq.org are called `winehq-stable`, `winehq-devel`, `winehq-staging`.
`wine32` is the name from the main repositories.

**Comment by jogness** [comment]
On 2024-11-13, Thomas Weißschuh ***@***.***> wrote:
> To be honest this does sound like a fringe usecase and I'm a bit
> reluctant to add first-class support for it.  I think the finetuning
> solution works well enough, no?

The only real problem is that packages installed via fine-tuning do not
end up on the ISO images. But really a separate issue for that should be
opened.

John Ogness
