### ISSUE TITLE
elbe v15.x: Parsing of elbe initvm options has changed but is not documented

### ISSUE THREAD

**Issue by dermaulwurfpauli** [Linutronix/elbe#421]
For a long time we used the following command to create an initvm:
`elbe initvm --directory /initvm create initvm.xml`

Since elbe v15 this error occurs: 
`usage: elbe initvm [-h] [-v VARIANTS] [-p PROXY] [--sshport SSHPORT]
                   [--soapport SOAPPORT] [-z GZIP]
                   {start,ensure,stop,destroy,attach,create,submit,sync} ...
elbe initvm: error: argument {start,ensure,stop,destroy,attach,create,submit,sync}: invalid choice: '/initvm' (choose from 'start', 'ensure', 'stop', 'destroy', 'attach', 'create', 'submit', 'sync')`

According to [elbe-initvm](https://elbe-rfs.org/docs/sphinx/v15.2/elbe-initvm.html) the option `--directory /initvm` is in the correct position.
It works if the option is put at the end of the command line.

**Comment by t-8ch** [comment]
Thanks for the report. This was also reported in #414.
I have a fix for the docs in https://lists.linutronix.de/pipermail/elbe-devel/2024-December/007592.html
