### ISSUE TITLE
elbe chroot alters files

### ISSUE THREAD

**Issue by manut** [Linutronix/elbe#58]
elbe chroot into an existing chroot or target directory alters files, e.g. /etc/apt/sources.list

This is caused by

```
    self.initialize_dirs (build_sources=build_sources)                      
```

in the BuildEnv constructor.

I'm afraid of moving this function without testing. It might affect pbuilder, etc

**Comment by torbenh3** [comment]
the excursion code added for the fixing of #199 should be taking care of this now
