### ISSUE TITLE
Copy a file from rfs to the build directory

### ISSUE THREAD

**Issue by iluminat23** [Linutronix/elbe#60]
It would be nice to be able to copy a file from the rfs to the build directory.

**Comment by jogness** [comment]
By "build directory" do you mean "project directory"? i.e. the parent of the chroot filesystem? I am curious why this would be nice. What is the use case?

**Comment by iluminat23** [comment]
I mean the directory where the images are saved (elbe-build-YYYYMMDD-hhmmss/). We create a rootfs.tar.gz which contains all files. We can extract for example the bootloader an the kernel image from there. But it would be nice if we could tell elbe to copy them to the build directory. So these files could be used directly.

**Comment by manut** [comment]
yes, this would be really useful.
I think it should be a move from the /target directory instead of a copy.
A new finetuning action might be used to implement this..

**Comment by iluminat23** [comment]
I think both would be nice to have. In my case I would need a copy, as the file should also stay in the image.

**Comment by manut** [comment]
fixed by c931f0eed
