### ISSUE TITLE
elbe-daemon sys.exit() on error

### ISSUE THREAD

**Issue by jogness** [Linutronix/elbe#61]
There are many places where the elbe-daemon will simply print() an error and then sys.exit(). For example, if an invalid buildtype is specified in the XML. This is a problem because:
1. The elbe-daemon is no longer running on the initvm.
2. No useful information about the error is communicated over the SOAP interface to the user.

**Comment by manut** [comment]
we need to properly replace elbepack/xmldefaults.py:ElbeDefaults:__init__: sys.exit(20) by an exception and handle this in all callers. The same for the sys.exit call in virtapt.py
