### ISSUE TITLE
simple helloworld.deb paket give [Errno 2]

### ISSUE THREAD

**Issue by goofy79** [Linutronix/elbe#75]
If i try to install the simple helloworld.deb paket example - the Build get an error
[http://www.tomprogs.at/tutorials/linux/debian-paket-tutorials-01-ein-erstes-paket.xhtml](url)

```
Server returned error:
OSError: [Errno 2] No such file or directory: '/var/cache/elbe/25aca17c-a186-4c42-b5f2-d92789ec515e/validation.txt'
Project failed to generate validation.txt
Getting log.txt
Enqueueing project for build
Build started
.
.
.
running cmd +chroot /var/cache/elbe/25aca17c-a186-4c42-b5f2-d92789ec515e/chroot dpkg --configure -a+
running cmd +chroot /var/cache/elbe/25aca17c-a186-4c42-b5f2-d92789ec515e/chroot debconf-set-selections < /var/cache/elbe/25aca17c-a186-4c42-b5f2-d92789ec515e/chroot/var/cache/elbe/preseed.txt+
update cache failed
Build failed !!!

Failed to build the Apt Cache.
Not all Mirror Index Files could be downloaded.
Probable cause might be:
- Problems with Internet Connection
- Broken mirrors
```

I build this package with "dpkg --build ./helloworld helloworld.deb" and put it on a internal repository. Other packages from this repository work fine.

**Comment by manut** [comment]
Failed to build the Apt Cache.
Not all Mirror Index Files could be downloaded.

is normally a hint, that your repo is corrupt. If the problem still exists, please try to get help via IRC
