### ISSUE TITLE
fixup overview examples

### ISSUE THREAD

**Issue by erickeller** [Linutronix/elbe#76]
Hi there I tried to go through your examples in the Create initvm and build a first xml file from the examples sections the following command does not work since the mini-wheezy-nfsroot.xml does not exist anymore.

```
elbe initvm create --directory ~/elbe-initvm /usr/share/doc/elbe-doc/examples/mini-wheezy-nfsroot.xml
```
Best regards

**Comment by manut** [comment]
thx for the report, i fixed the document and regenerated the website
