### ISSUE TITLE
support multiarch

### ISSUE THREAD

**Issue by manut** [Linutronix/elbe#81]
<finetuning>
  <command>dpkg --add-architecture armel</command>
  <command>apt-get update</command>
  <command>apt-get install libc6:armel</command>
  ...
</finetuning>

is not perfect. src and binary packages won't be stored on the cdrom images.

**Comment by manut** [comment]
if implementing, take care on validation:

http://lists.linutronix.de/pipermail/elbe-devel/2017-December/000780.html

**Comment by bgermann** [comment]
Will not implement.
