### ISSUE TITLE
contrib: Keep the debian directory after debianizing the kernel.

### ISSUE THREAD

**Issue by richardcochran** [Linutronix/elbe#87]
The normal Linux build process ignores debian/ and even deletes it on 'make mrproper'.
After going through the trouble to debianize a kernel, we really want to keep that
directory around.  This patch does that.

The patch is against the Linux kernel (not against elbe!), and so it could be added
under elbe/contrib/linux or even folded into
0001-debian-workaround-broken-installkernel-in-jessie.patch

(Patch applies on kernel v4.3 or newer.)

Thanks,
Richard

[0002-Treat-the-debian-directory-as-precious.patch.txt](https://github.com/Linutronix/elbe/files/693520/0002-Treat-the-debian-directory-as-precious.patch.txt)

**Comment by manut** [comment]
integrated with 210fb7ff305f61ae670cfd3aea03f2389867b80d
