### ISSUE TITLE
The kernel debianizing patch in contrib/linux is incomplete.

### ISSUE THREAD

**Issue by richardcochran** [Linutronix/elbe#88]
The patch

    contrib/linux/0001-debian-workaround-broken-installkernel-in-jessie.patch

on branch

    devel/elbe-2.0

is only for x86.  It really should also fix arm (by patching arch/arm/boot/install.sh)
and any other supports archs.

Thanks,
Richard

**Comment by manut** [comment]
fixed by jogness: 37869b911a5bb1e9521c62ec05372602646b335f
