### ISSUE TITLE
transitional and removed packages in debian stretch

### ISSUE THREAD

**Issue by bene42** [Linutronix/elbe#90]
- python-pyme is superseeded by python-gpg and was removed from debian stretch.
- dh-systemd is now part of debhelper.

**Comment by manut** [comment]
python-pyme: think about providing a transitional package for strecht/sid via elbe-common

dh-systemd: keep the dependency until jessie is not needed to be supproted to avoid maintaining different elbe branches for different debian releases.

**Comment by manut** [comment]
fixed by 05c797a and dddad87c6c2902599459fbe08813ade571917597
