### ISSUE TITLE
elbe submit: error not helpfull on initvm and host elbe version missmatch

### ISSUE THREAD

**Issue by iluminat23** [Linutronix/elbe#99]
If the version of elbe in the initvm and on the host differ `elbe submit` shows a generic. 
`elbe control create_project failed.`
`Giving up`
It should show something like `elbe control` does:
`elbe control create_project `
`elbe v1.9.19 is used in initvm, this is not compatible with elbe v1.9.18 that is used on this machine. Please install same versions of elbe in initvm and on your machine.`

**Comment by manut** [comment]
fixed by Phillip Arras: 6af313f5afcaad1051b1494ca200b1717153e47d
